-- Migration: Add Step 4 editable fields to use_cases table
-- Generated by: drizzle-kit generate
-- Modified by: Anil - Added IF NOT EXISTS for idempotency
-- Date: 2024-12-30

ALTER TABLE "use_cases" ADD COLUMN IF NOT EXISTS "name" text;--> statement-breakpoint
ALTER TABLE "use_cases" ADD COLUMN IF NOT EXISTS "category" text;--> statement-breakpoint
ALTER TABLE "use_cases" ADD COLUMN IF NOT EXISTS "problem" text;--> statement-breakpoint
ALTER TABLE "use_cases" ADD COLUMN IF NOT EXISTS "agent_role" text;--> statement-breakpoint
ALTER TABLE "use_cases" ADD COLUMN IF NOT EXISTS "data_required" text;--> statement-breakpoint
ALTER TABLE "use_cases" ADD COLUMN IF NOT EXISTS "integration" text;